name: FastAPI CI/CD

on:
  # Trigger when code is pushed
  push:
    branches:
      - dev

jobs:

  CI:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Set up Python

        uses: actions/setup-python@v2
        with:
          python-version: 3.8

      - name: Install Python Virtual ENV
        run: pip3 install virtualenv

      - name: Virtual ENV
        uses: actions/cache@v2
        id: cache-venv
        with:
          path: venv
          key: ${{ runner.os }}-venv-${{ hashFiles('**/requirements*.txt') }}
          restore-keys: |
            ${{ runner.os }}-venv-

      - name: Activate Virtual ENV
        run: python -m venv venv && source venv/bin/activate && pip3 install -r requirements.txt
        if: steps.cache-venv.outputs.cache-hit != 'true'

      - name: Run Tests
        run: . venv/bin/activate && pytest

      - name: Create archive of dependencies
        run: |
          cd ./venv/lib/python3.8/site-packages
          zip -r9 ../../../../api.zip .
      
      - name: Add API files to Zip file
        run: cd ./api && zip -g ../api.zip -r .

      - name: Upload zip file artifact
        uses: actions/upload-artifact@v2aws
        with:
          name: api
          path: api.zip

  CD:
    runs-on: ubuntu-latest
    needs: [CI]
    if: github.ref == 'refs/heads/dev' && github.event_name == 'push'
    steps:
      - name: Install AWS CLI
        uses: unfor19/install-aws-cli-action@v1
        with: 
          version: 1
        env:
          AWS_ACCESS_KEY_ID: ${{ secret.AWS_SECRET_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secret.AWS_SECRET_ACCESS_KEY }}
          AWS_DEFAULT_REGION: ${{ secret.AWS_DEFAULT_REGION }}

      - name: Download Lambda api.zip
        uses: actions/download-artifact@v2
        with: 
          name: api
      
      - name: Upload to S3 bucket
        run: aws s3 cp api.zip s3://serverless-python-fastapi/api.zip
        env: 
          AWS_ACCESS_KEY_ID: ${{ secret.AWS_SECRET_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secret.AWS_SECRET_ACCESS_KEY }}
          AWS_DEFAULT_REGION: ${{ secret.AWS_DEFAULT_REGION }}

      - name: Deploy new Lambda
        run: aws lambda update-function-code --function-name serverless-python-fastapi --s3-bucket serverless-python-fastapi --s3-key api.zip
        env: 
          AWS_ACCESS_KEY_ID: ${{ secret.AWS_SECRET_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secret.AWS_SECRET_ACCESS_KEY }}
          AWS_DEFAULT_REGION: ${{ secret.AWS_DEFAULT_REGION }}